add_test( [==[SetBitIterator tests]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[SetBitIterator tests]==]  )
set_tests_properties( [==[SetBitIterator tests]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelSlopeAdditionTest - A one corner slope, plus the opposite three corner slope results in a flat but elevated slope]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelSlopeAdditionTest - A one corner slope\, plus the opposite three corner slope results in a flat but elevated slope]==]  )
set_tests_properties( [==[PartialPixelSlopeAdditionTest - A one corner slope, plus the opposite three corner slope results in a flat but elevated slope]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelSlopeAdditionTest - Diagonal slopes with their opposite slope result in a flat but elevated slope]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelSlopeAdditionTest - Diagonal slopes with their opposite slope result in a flat but elevated slope]==]  )
set_tests_properties( [==[PartialPixelSlopeAdditionTest - Diagonal slopes with their opposite slope result in a flat but elevated slope]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelSlopeAdditionTest - Half tile slopes with their opposite half tile slope result in a flat but elevated slope]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelSlopeAdditionTest - Half tile slopes with their opposite half tile slope result in a flat but elevated slope]==]  )
set_tests_properties( [==[PartialPixelSlopeAdditionTest - Half tile slopes with their opposite half tile slope result in a flat but elevated slope]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelSlopeAdditionTest - Two opposite one corner slopes result in the two corner slope with opposite corners]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelSlopeAdditionTest - Two opposite one corner slopes result in the two corner slope with opposite corners]==]  )
set_tests_properties( [==[PartialPixelSlopeAdditionTest - Two opposite one corner slopes result in the two corner slope with opposite corners]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelSlopeAdditionTest - A steep slope is a one corner slope on top of a three corner slope]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelSlopeAdditionTest - A steep slope is a one corner slope on top of a three corner slope]==]  )
set_tests_properties( [==[PartialPixelSlopeAdditionTest - A steep slope is a one corner slope on top of a three corner slope]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelSlopeAdditionTest - A half tile steep slope is a one corner half tile on top of a three corner slope]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelSlopeAdditionTest - A half tile steep slope is a one corner half tile on top of a three corner slope]==]  )
set_tests_properties( [==[PartialPixelSlopeAdditionTest - A half tile steep slope is a one corner half tile on top of a three corner slope]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - One corner up slopes - SLOPE_N]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - One corner up slopes - SLOPE_N]==]  )
set_tests_properties( [==[PartialPixelTest - One corner up slopes - SLOPE_N]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - One corner up slopes - SLOPE_E]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - One corner up slopes - SLOPE_E]==]  )
set_tests_properties( [==[PartialPixelTest - One corner up slopes - SLOPE_E]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - One corner up slopes - SLOPE_S]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - One corner up slopes - SLOPE_S]==]  )
set_tests_properties( [==[PartialPixelTest - One corner up slopes - SLOPE_S]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - One corner up slopes - SLOPE_W]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - One corner up slopes - SLOPE_W]==]  )
set_tests_properties( [==[PartialPixelTest - One corner up slopes - SLOPE_W]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_NE]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Two corner up\, diagonal slopes - SLOPE_NE]==]  )
set_tests_properties( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_NE]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_SE]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Two corner up\, diagonal slopes - SLOPE_SE]==]  )
set_tests_properties( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_SE]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_SW]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Two corner up\, diagonal slopes - SLOPE_SW]==]  )
set_tests_properties( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_SW]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_NW]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Two corner up\, diagonal slopes - SLOPE_NW]==]  )
set_tests_properties( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_NW]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_NS]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_NS]==]  )
set_tests_properties( [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_NS]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_EW]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_EW]==]  )
set_tests_properties( [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_EW]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Three corner up slopes - SLOPE_ENW]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Three corner up slopes - SLOPE_ENW]==]  )
set_tests_properties( [==[PartialPixelTest - Three corner up slopes - SLOPE_ENW]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Three corner up slopes - SLOPE_SEN]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Three corner up slopes - SLOPE_SEN]==]  )
set_tests_properties( [==[PartialPixelTest - Three corner up slopes - SLOPE_SEN]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Three corner up slopes - SLOPE_WSE]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Three corner up slopes - SLOPE_WSE]==]  )
set_tests_properties( [==[PartialPixelTest - Three corner up slopes - SLOPE_WSE]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Three corner up slopes - SLOPE_NWS]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Three corner up slopes - SLOPE_NWS]==]  )
set_tests_properties( [==[PartialPixelTest - Three corner up slopes - SLOPE_NWS]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_N]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_N]==]  )
set_tests_properties( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_N]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_E]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_E]==]  )
set_tests_properties( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_E]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_S]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_S]==]  )
set_tests_properties( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_S]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_W]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_W]==]  )
set_tests_properties( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_W]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_N]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_N]==]  )
set_tests_properties( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_N]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_E]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_E]==]  )
set_tests_properties( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_E]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_S]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_S]==]  )
set_tests_properties( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_S]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_W]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_W]==]  )
set_tests_properties( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_W]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_N]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_N]==]  )
set_tests_properties( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_N]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_E]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_E]==]  )
set_tests_properties( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_E]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_S]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_S]==]  )
set_tests_properties( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_S]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_W]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_W]==]  )
set_tests_properties( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_W]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[DivideApproxTest - Negative]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[DivideApproxTest - Negative]==]  )
set_tests_properties( [==[DivideApproxTest - Negative]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[DivideApproxTest, Divide]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[DivideApproxTest\, Divide]==]  )
set_tests_properties( [==[DivideApproxTest, Divide]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[IntSqrtTest - Zero]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[IntSqrtTest - Zero]==]  )
set_tests_properties( [==[IntSqrtTest - Zero]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[IntSqrtTest - FindSqRt]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[IntSqrtTest - FindSqRt]==]  )
set_tests_properties( [==[IntSqrtTest - FindSqRt]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( ClampTo /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js ClampTo  )
set_tests_properties( ClampTo PROPERTIES WORKING_DIRECTORY /src/build)
add_test( SoftClamp /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js SoftClamp  )
set_tests_properties( SoftClamp PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrCompareIgnoreCase - std::string]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrCompareIgnoreCase - std::string]==]  )
set_tests_properties( [==[StrCompareIgnoreCase - std::string]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrCompareIgnoreCase - char pointer]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrCompareIgnoreCase - char pointer]==]  )
set_tests_properties( [==[StrCompareIgnoreCase - char pointer]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrCompareIgnoreCase - std::string_view]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrCompareIgnoreCase - std::string_view]==]  )
set_tests_properties( [==[StrCompareIgnoreCase - std::string_view]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrEqualsIgnoreCase - std::string]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrEqualsIgnoreCase - std::string]==]  )
set_tests_properties( [==[StrEqualsIgnoreCase - std::string]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrEqualsIgnoreCase - char pointer]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrEqualsIgnoreCase - char pointer]==]  )
set_tests_properties( [==[StrEqualsIgnoreCase - char pointer]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrEqualsIgnoreCase - std::string_view]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrEqualsIgnoreCase - std::string_view]==]  )
set_tests_properties( [==[StrEqualsIgnoreCase - std::string_view]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrStartsWithIgnoreCase - std::string]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrStartsWithIgnoreCase - std::string]==]  )
set_tests_properties( [==[StrStartsWithIgnoreCase - std::string]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrStartsWithIgnoreCase - char pointer]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrStartsWithIgnoreCase - char pointer]==]  )
set_tests_properties( [==[StrStartsWithIgnoreCase - char pointer]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrStartsWithIgnoreCase - std::string_view]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrStartsWithIgnoreCase - std::string_view]==]  )
set_tests_properties( [==[StrStartsWithIgnoreCase - std::string_view]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrEndsWithIgnoreCase - std::string]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrEndsWithIgnoreCase - std::string]==]  )
set_tests_properties( [==[StrEndsWithIgnoreCase - std::string]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrEndsWithIgnoreCase - char pointer]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrEndsWithIgnoreCase - char pointer]==]  )
set_tests_properties( [==[StrEndsWithIgnoreCase - char pointer]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrEndsWithIgnoreCase - std::string_view]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrEndsWithIgnoreCase - std::string_view]==]  )
set_tests_properties( [==[StrEndsWithIgnoreCase - std::string_view]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( FormatArrayAsHex /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js FormatArrayAsHex  )
set_tests_properties( FormatArrayAsHex PROPERTIES WORKING_DIRECTORY /src/build)
add_test( ConvertHexToBytes /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js ConvertHexToBytes  )
set_tests_properties( ConvertHexToBytes PROPERTIES WORKING_DIRECTORY /src/build)
add_test( HaveDParamChanged /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js HaveDParamChanged  )
set_tests_properties( HaveDParamChanged PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[Squirrel -> JSON conversion]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[Squirrel -> JSON conversion]==]  )
set_tests_properties( [==[Squirrel -> JSON conversion]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[JSON -> Squirrel conversion]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[JSON -> Squirrel conversion]==]  )
set_tests_properties( [==[JSON -> Squirrel conversion]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[WindowDesc - ini_key uniqueness]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[WindowDesc - ini_key uniqueness]==]  )
set_tests_properties( [==[WindowDesc - ini_key uniqueness]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[WindowDesc - ini_key validity]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[WindowDesc - ini_key validity]==]  )
set_tests_properties( [==[WindowDesc - ini_key validity]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[WindowDesc - NWidgetParts properly closed]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[WindowDesc - NWidgetParts properly closed]==]  )
set_tests_properties( [==[WindowDesc - NWidgetParts properly closed]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[WindowDesc - NWidgetPart validity]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[WindowDesc - NWidgetPart validity]==]  )
set_tests_properties( [==[WindowDesc - NWidgetPart validity]==] PROPERTIES WORKING_DIRECTORY /src/build)
set( openttd_test_TESTS [==[SetBitIterator tests]==] [==[PartialPixelSlopeAdditionTest - A one corner slope, plus the opposite three corner slope results in a flat but elevated slope]==] [==[PartialPixelSlopeAdditionTest - Diagonal slopes with their opposite slope result in a flat but elevated slope]==] [==[PartialPixelSlopeAdditionTest - Half tile slopes with their opposite half tile slope result in a flat but elevated slope]==] [==[PartialPixelSlopeAdditionTest - Two opposite one corner slopes result in the two corner slope with opposite corners]==] [==[PartialPixelSlopeAdditionTest - A steep slope is a one corner slope on top of a three corner slope]==] [==[PartialPixelSlopeAdditionTest - A half tile steep slope is a one corner half tile on top of a three corner slope]==] [==[PartialPixelTest - One corner up slopes - SLOPE_N]==] [==[PartialPixelTest - One corner up slopes - SLOPE_E]==] [==[PartialPixelTest - One corner up slopes - SLOPE_S]==] [==[PartialPixelTest - One corner up slopes - SLOPE_W]==] [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_NE]==] [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_SE]==] [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_SW]==] [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_NW]==] [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_NS]==] [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_EW]==] [==[PartialPixelTest - Three corner up slopes - SLOPE_ENW]==] [==[PartialPixelTest - Three corner up slopes - SLOPE_SEN]==] [==[PartialPixelTest - Three corner up slopes - SLOPE_WSE]==] [==[PartialPixelTest - Three corner up slopes - SLOPE_NWS]==] [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_N]==] [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_E]==] [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_S]==] [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_W]==] [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_N]==] [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_E]==] [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_S]==] [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_W]==] [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_N]==] [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_E]==] [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_S]==] [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_W]==] [==[DivideApproxTest - Negative]==] [==[DivideApproxTest, Divide]==] [==[IntSqrtTest - Zero]==] [==[IntSqrtTest - FindSqRt]==] ClampTo SoftClamp [==[StrCompareIgnoreCase - std::string]==] [==[StrCompareIgnoreCase - char pointer]==] [==[StrCompareIgnoreCase - std::string_view]==] [==[StrEqualsIgnoreCase - std::string]==] [==[StrEqualsIgnoreCase - char pointer]==] [==[StrEqualsIgnoreCase - std::string_view]==] [==[StrStartsWithIgnoreCase - std::string]==] [==[StrStartsWithIgnoreCase - char pointer]==] [==[StrStartsWithIgnoreCase - std::string_view]==] [==[StrEndsWithIgnoreCase - std::string]==] [==[StrEndsWithIgnoreCase - char pointer]==] [==[StrEndsWithIgnoreCase - std::string_view]==] FormatArrayAsHex ConvertHexToBytes HaveDParamChanged [==[Squirrel -> JSON conversion]==] [==[JSON -> Squirrel conversion]==] [==[WindowDesc - ini_key uniqueness]==] [==[WindowDesc - ini_key validity]==] [==[WindowDesc - NWidgetParts properly closed]==] [==[WindowDesc - NWidgetPart validity]==])
